# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RACCode' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for RACCode
pod 'AFNetworking', '~> 3.0’  
pod 'Masonry', '~> 0.6.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ReactiveCocoa','~>2.1.8'
end
